// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"sns-server/internal/models"
)

type AuthResponse struct {
	Token string       `json:"token"`
	User  *models.User `json:"user"`
}

type CreatePostInput struct {
	Content  string  `json:"content"`
	ParentID *string `json:"parentId,omitempty"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterInput struct {
	Username string  `json:"username"`
	Email    string  `json:"email"`
	Password string  `json:"password"`
	Name     string  `json:"name"`
	Bio      *string `json:"bio,omitempty"`
}

type Timeline struct {
	Posts       []*models.Post `json:"posts"`
	HasNextPage bool           `json:"hasNextPage"`
	Cursor      *string        `json:"cursor,omitempty"`
}

type UpdateProfileInput struct {
	Name   *string `json:"name,omitempty"`
	Bio    *string `json:"bio,omitempty"`
	Avatar *string `json:"avatar,omitempty"`
}
